message: "§8[§c✘§8] §c你没权限"
debug: false
WRENCHES:
  - CREATE_WRENCH
  - POWAH_WRENCH
  - TECHREBORN_WRENCH
  - AE2_CERTUS_QUARTZ_WRENCH
  - AE2_NETHER_QUARTZ_WRENCH
  - ADVANCED_REBORN_CONFIG_WRENCH
  - INDREV_WRENCH
  - MODERN_INDUSTRIALIZATION_WRENCH